### ISSUE TITLE
Renci.SshNet.Common.SshConnectionException

### ISSUE THREAD

**Issue by yuriw** [Corsinvest/cv4pve-node-protect#4]
I've been using this script for a couple of years, but it started failing lately.  Maybe after pve 8 upgrade

/usr/bin/cv4pve-node-protect --host=192.168.990.127 --username=XYZ --password=XYA backup --keep 3 --directory-work "/home/***/Dropbox/Things/XYZ/etc/."  --paths "/etc/pve/lxc/." --paths "/etc/pve/qemu-server/." --paths "/etc/pve/storage.cfg"
ACTION Backup
Keep: 3
Directory Work: /home/XYZ/XYZ.net_backup
Directory Node to archive:
/etc/.
/etc/pve/lxc/.
/etc/pve/qemu-server/.
/etc/pve/storage.cfg
================ EXCEPTION ================ 
Renci.SshNet.Common.SshConnectionException
An established connection was aborted by the server.
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()
   at Corsinvest.ProxmoxVE.NodeProtect.Api.Application.Backup(String hostsAndPort, String username, String password, String[] pathsToBackup, String directoryWork, Int32 keep, Boolean debug, TextWriter out)
   at Corsinvest.ProxmoxVE.NodeProtect.ShellCommands.<>c__DisplayClass2_1.<Backup>b__2()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.ShellHelper.ExecuteConsoleApp(CommandLineApplication app, String[] args)

Any help is appreciated.
TIA

**Comment by franklupo** [comment]
Hi,
run command with --debug and atattach log

best regards

**Comment by yuriw** [comment]
@franklupo pls see below:

================ EXCEPTION ================ 
Renci.SshNet.Common.SshConnectionException
An established connection was aborted by the server.
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()
   at Corsinvest.ProxmoxVE.NodeProtect.Api.Application.Backup(String hostsAndPort, String username, String password, String[] pathsToBackup, String directoryWork, Int32 keep, Boolean debug, TextWriter out)
   at Corsinvest.ProxmoxVE.NodeProtect.ShellCommands.<>c__DisplayClass2_1.<Backup>b__2()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.ShellHelper.ExecuteConsoleApp(CommandLineApplication app, String[] args)
================ EXCEPTION ================ 
Renci.SshNet.Common.SshConnectionException
An established connection was aborted by the server.
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()
   at Corsinvest.ProxmoxVE.NodeProtect.Api.Application.Backup(String hostsAndPort, String username, String password, String[] pathsToBackup, String directoryWork, Int32 keep, Boolean debug, TextWriter out)
   at Corsinvest.ProxmoxVE.NodeProtect.ShellCommands.<>c__DisplayClass2_1.<Backup>b__2()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.ShellHelper.ExecuteConsoleApp(CommandLineApplication app, String[] args)

**Comment by franklupo** [comment]
The default port ssl is 22?

**Comment by yuriw** [comment]
Yes

**Comment by franklupo** [comment]
The version is 8?

**Comment by yuriw** [comment]
Yes

**Comment by franklupo** [comment]
can you connect to ssh?
which version of cv4pve-node-protect are you using ?

**Comment by yuriw** [comment]
/usr/bin/cv4pve-node-protect --version

    ______                _                      __
   / ____/___  __________(_)___ _   _____  _____/ /_
  / /   / __ \/ ___/ ___/ / __ \ | / / _ \/ ___/ __/
 / /___/ /_/ / /  (__  ) / / / / |/ /  __(__  ) /_
 \____/\____/_/  /____/_/_/ /_/|___/\___/____/\__/


Node protect for Proxmox VE                    (Made in Italy)
1.1.4


I can `ssh` to my `pve` server.

I've used it for a long time with no modification, it was scheduled from `crontab`, and after upgrading to proxmox 8 I was interested in more protection and noticed that the scrip's tar file was empty.  Then track it to the date when my server was upgraded.  Before that date I had no issues.

**Comment by franklupo** [comment]
try last version https://github.com/Corsinvest/cv4pve-node-protect/releases/tag/v1.2.1

**Comment by yuriw** [comment]
@franklupo that seems to work

Thx!

I think some syntax changed 

If I used: `--paths /etc/pve; /etc/pve/lxc`
I get
Directory Node to archive:
/etc/pve
Create config: /home/XYA/Dropbox/XXX/YYY_backup/2023-07-19-12-47-25/192.168.90.7-config.tar.gz
Delete Backup: /home/XYA/Dropbox/XXX/XXX.net_backup/2023-07-19-12-45-08
-bash: /etc/pve/lxc: No such file or directory

But I will have to play with it.
